apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-headless
  labels:
    purpose: statefulset
    project: roboshop
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    purpose: statefulset
    project: roboshop
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-normal
  labels:
    purpose: statefulset
    project: roboshop
spec:
  selector:
    purpose: statefulset
    project: roboshop
  ports:
  - port: 80
    name: web
---
apiVersion: v1
kind: statefulset
metadata:
  name: sc-headless
  labels:
    purpose: statefulset
    project: roboshop
spec:
  selector:
    matchLabels:
      purpose: statefulset  # has to match .spec.template.metadata.labels
      project: roboshop
  serviceName: "nginx-svc-headless"  # this should be headless service
  replicas: 3
  template:
    metadata:
      labels:
        purpose: statefulset
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html
  # This is nothing but PVC, you can directly create here
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "efs-roboshop"
      resources:
        requests:
          storage: 2Gi